export const DEVICES = [
  'custom',
  'iPad (gen 7)',
  'iPad (gen 7) landscape',
  'iPad Mini',
  'iPad Mini landscape',
  // "iPad Pro 11",
  //   "iPad Pro 11 landscape",
  'iPhone SE',
  'iPhone SE landscape',
  'iPhone 12',
  'iPhone 12 landscape',
  'iPhone 12 Pro',
  'iPhone 12 Pro landscape',
  'iPhone 12 Pro Max',
  'iPhone 12 Pro Max landscape',
  'iPhone 12 Mini',
  'iPhone 12 Mini landscape',
  'iPhone 13',
  'iPhone 13 landscape',
  'iPhone 13 Pro',
  'iPhone 13 Pro landscape',
  'iPhone 13 Pro Max',
  'iPhone 13 Pro Max landscape',
  'iPhone 13 Mini',
  'iPhone 13 Mini landscape',
  //   'iPhone 14',
  //   'iPhone 14 landscape',
  //   'iPhone 14 Plus',
  //   'iPhone 14 Plus landscape',
  //   'iPhone 14 Pro',
  //   'iPhone 14 Pro landscape',
  //   'iPhone 14 Pro Max',
  //   'iPhone 14 Pro Max landscape',
  'Pixel 5',
  'Pixel 5 landscape'
  //   'Pixel 7',
  //   'Pixel 7 landscape'
]
